import BaseLayout from "@/components/BaseLayout";
import ParameterMap from "@/components/ParameterMap";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Map - Trafo Monitoring Dashboard",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <BaseLayout searchBar={true}>
      <div>
        <ParameterMap />
      </div>
    </BaseLayout>
  );
}
