import BaseLayout from "@/components/BaseLayout";
import Graph from "@/components/Graph";
import { Metadata } from "next";
import React from "react";
import "react-day-picker/style.css";

export const metadata: Metadata = {
  title: "Graph - Trafo Monitoring Dashboard",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <BaseLayout searchBar={false} className="pb-1">
      <Graph />
    </BaseLayout>
  );
}
